## QQ邮箱配置
spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1121195084@qq.com #发送邮件的邮箱地址
    password: wuasyfiqaqyxjfad #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 1121195084@qq.com # 发送邮件的地址，和上面username一致
    templateName: mail2 #邮件模板名称
    #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8